// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Truck.Infra.Database;

namespace Truck.Infra.Database.Migrations
{
    [DbContext(typeof(TruckContext))]
    [Migration("20190521171441_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Truck.Infra.Database.Entities.ColorOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte>("Blue");

                    b.Property<byte>("Green");

                    b.Property<string>("Name");

                    b.Property<byte>("Red");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Blue = (byte)0,
                            Green = (byte)0,
                            Name = "Vermelho",
                            Red = (byte)255
                        },
                        new
                        {
                            Id = 2,
                            Blue = (byte)255,
                            Green = (byte)0,
                            Name = "Azul",
                            Red = (byte)0
                        },
                        new
                        {
                            Id = 3,
                            Blue = (byte)0,
                            Green = (byte)255,
                            Name = "Verde",
                            Red = (byte)0
                        },
                        new
                        {
                            Id = 4,
                            Blue = (byte)6,
                            Green = (byte)255,
                            Name = "Amarelo",
                            Red = (byte)255
                        },
                        new
                        {
                            Id = 5,
                            Blue = (byte)51,
                            Green = (byte)153,
                            Name = "Laranja",
                            Red = (byte)255
                        },
                        new
                        {
                            Id = 6,
                            Blue = (byte)169,
                            Green = (byte)169,
                            Name = "Cinza",
                            Red = (byte)169
                        });
                });

            modelBuilder.Entity("Truck.Infra.Database.Entities.ModelOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "FH"
                        },
                        new
                        {
                            Id = 2,
                            Name = "FM"
                        });
                });

            modelBuilder.Entity("Truck.Infra.Database.Entities.Truck", b =>
                {
                    b.Property<string>("Chassis")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ColorId");

                    b.Property<int>("ManufactureYear");

                    b.Property<int>("ModelId");

                    b.Property<int>("ModelYear");

                    b.Property<int>("Type");

                    b.HasKey("Chassis");

                    b.HasIndex("ColorId");

                    b.HasIndex("ModelId");

                    b.ToTable("Trucks");
                });

            modelBuilder.Entity("Truck.Infra.Database.Entities.Truck", b =>
                {
                    b.HasOne("Truck.Infra.Database.Entities.ColorOption", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Truck.Infra.Database.Entities.ModelOption", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
